GROQ_API_KEY_1="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"
GROQ_API_KEY_2="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"
GROQ_API_KEY_3="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"
GROQ_API_KEY_4="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"
GROQ_API_KEY_5="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"
GROQ_API_KEY_6="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"
GROQ_API_KEY_7="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"
GROQ_API_KEY_8="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"
GROQ_API_KEY_9="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"
GROQ_API_KEY_10="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"

GOOGLE_API_KEY = "AIzaSyBYYkerBt4dSbG2Ounu5E8trA7oU0pmkUw"
GOOGLE_CSE_ID = "6254c7d8d029a4eb7"
